deel_project:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: mboszhi-uq78868
      user: martareda
      password: 23922martaR
      role: accountadmin
      database: prod
      warehouse: compute_wh
      schema: lkh
      threads: 1
      client_session_keep_alive: False    
    raw_prod:
      type: snowflake
      account: mboszhi-uq78868
      user: martareda
      password: 23922martaR
      role: accountadmin
      database: raw_prod
      warehouse: compute_wh
      threads: 1
      client_session_keep_alive: False